# Generated by Django 2.0 on 2018-10-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_periodictransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodictransfer',
            name='transfer_ptr',
        ),
        migrations.DeleteModel(
            name='PeriodicTransfer',
        ),
    ]
